Implement conquest duration
Kalaxia/v2-api pull request #48
Opened 2020-12-27 14:47 UTC by Kern046

2021-03-04 21:34 UTC, ablanleuil requested changes
Je n'ai review que le truc de `add_task` parce que je trouve que c'est peut-être un faux ami pour ce que tu sembles vouloir faire. On peut reflechir ensemble à comment implem ce que tu veux mais faudra passer par un peu plus de reflexion avant de coder peut-être ^^

2021-03-04 21:34 UTC, ablanleuil commented on src/game/game/server.rs
> +        self.add_task(ctx, "income".to_string(), Duration::new(5, 0), move |this, _| {
Les tasks `"income"` et `"Victory points"` sont des tâches à intervalles. Là tu cré une task one shot. C'est quoi le but de ton système de task en fait ? je vois pas l'intérêt, à part peut-être factoriser le logging, ce que tu pourrais faire plutôt avec une fonction de log à part du style:
```rust
fn log_result<T>(res: Result<T>) -> Result<T> {
  res.map_err(|e| {
    println!("{:?}", e);
    e
  })
}
```

Que tu utiliserai comme ceci:
```rust
self.run_later(Duration::new(1, 0) |this, _| {
  log_result(block_on(this.init()).map_err(ServerError::from));
});
```

De ce que je comprend, une task c'est un truc à exécuter au bout d'un certain temps, mais que tu peux annuler à tout moment de n'importe-où dans le code. C'est ça ?
Si oui, est-ce que tu peux me citer une chose qui doit avoir ce comportement dans le jeu ? Peut-être que le système peut être perfectionné/corrigé.

2021-03-04 21:34 UTC, ablanleuil commented on src/game/game/server.rs
> +        self.add_task(ctx, "income".to_string(), Duration::new(5, 0), move |this, _| {
Tu as un là, `add_task` ne cré que des tâches one shot mais tu l'utilises pour des tâches périodiques (`run_interval`).

Est-ce que tu peux m'expliquer à quoi te sert le système de tâche que tu as implémenté ? Est-ce que c'est pour pouvoir avoir des tâches qui peuvent être annulées de n'importe-où dans le code ?
Si oui, est-ce que tu peux me citer un exemple dans le jeu qui aurait besoin de ça ? parce que je ne penses pas que init, begin, ou même des tâches périodiques comme income aient besoin d'un tel système.

Si tu voulais factoriser le log des erreurs, autant passer par une fonction auxiliaire du type:
```rust
fn log_err<T>(res:Result<T>) -> Result<T> {
  res.map_err(|e| { println!("{:?}", e); e })
}
```

2021-03-04 21:34 UTC, ablanleuil commented on src/game/game/server.rs
> +    pub fn cancel_task(&mut self, task_name: String) {
C'est mieux d'envoyer ta `String` par référence directement, et la remarque vaut aussi pour `remove_task`, ça te permet de ne pas avoir à cloner.

Aussi, on peut questionner la pertinence des `String` comme type pour le nom d'une tâche. Est-ce que tu veux pouvoir créer dynamiquement des identifiants pour tes tasks ? Du genre:
```rust
for x in 0..10 {
  let name = format!("Ma tache numero {}", x);
  self.add_task(name, todo!() /* la tache en elle meme */);
}
```

Aussi: Si tu ne fait que détruire le `SpawnHandle` renvoyé par ton [`run_later`](https://docs.rs/actix/0.10.0/actix/trait.AsyncContext.html#method.run_later) il va continuer la tâche quand même. Il faut utiliser la fonction [`cancel_future`](https://docs.rs/actix/0.10.0/actix/trait.AsyncContext.html#tymethod.cancel_future) donc il te faut le contexte d'execution

2021-03-04 21:34 UTC, ablanleuil commented on src/game/game/server.rs
> +    pub fn remove_task(&mut self, task_name: String) {
Je ne comprend pas l'utilité d'avoir un `cancel` et un `remove` task. Peux-tu m'expliquer la différence ?

2021-04-26 17:36 UTC, Kern046 commented on src/game/game/server.rs
> +    pub fn remove_task(&mut self, task_name: String) {
remove est appelé que la tâche ait été réalisée ou non (notamment par le callback implémenté dans ``add_task``). Cancel permet de d'abord appeler cancel_future sur le contexte puis de supprimer la tâche de la pile

2021-05-02 20:17 UTC, merged